version: '3.0'

services:
    website-customer:
        image: ngapham0705/website-customer:latest
        container_name: website-customer
        restart: always
        volumes:
            - data:/var/lib/website-customer
            - ./upload:/upload
        ports:
            - 80:80
        environment:
            - ConnectionString__Server=${MYSQL_SERVER}
            - ConnectionString__Database=${MYSQL_DATABASE}
            - ConnectionString__UserId=${MYSQL_ROOT_USER}
            - ConnectionString__Password=${MYSQL_ROOT_PASSWORD}
            - ConnectionString__Port= 3306
            - ConnectionString__Version=8.0.33
            - JWT__SecurityKey=ABC_C421AAEE0D114E9C
            - JWT__ValidIssuer=ABC
            - JWT__ValidAudience=ABC
            - JWT__Expires=1
            - JWT__ExpiresRefreshToken=2
            - Upload__Folder=/upload
            - Upload__Url=http://localhost:5000/api/file/{0}/{1}
            - ASPNETCORE_URLS=http://0.0.0.0:80
volumes:
    data:
  